### ISSUE TITLE
Searching by Commit Hash may return wrong result

### ISSUE THREAD

**Issue by cagdas001** [billsedison/vscode-gitlens#115]
**Describe the bug**
Search by commit hash functionality in the Commit Search view may return wrong results.

**To Reproduce**
1. Clone the test repo from BitBucket.
```sh
git clone https://bitbucket.org/billsedison/gitlens-test.git
```
2. Open the test repo folder in VSCode with *Open Folder*
3. Go to the *Commit Search* view
4. In the *enter commit hash* field, type **28be4683** and click *Search*
5. It will return the wrong commit. Find the information for commit **28be4683** in screenshots

**Expected behavior**
Searching by commit hash should return the exact match of given hash

**Screenshots**
 ![commit_info](https://gitlab.com/aggregated-git-diff/aggregated-git-diff-bug-bash/uploads/b2782d7f990076a798bb979e5b8a2a93/image.png)

**Additional context**
Provided in the PR (#114)  description.

**Comment by billsedison** [comment]
Good catch, thanks.
