### ISSUE TITLE
Focus Issue after Hiding the Electron App

### ISSUE THREAD

**Issue by cagdas001** [billsedison/vscode-gitlens#72]
**Describe the bug**
After hiding the electron app, the previously active window doesn't get the focus.

**To Reproduce**
Make sure **External App: Keep Open** parameter checked in **User Settings**, otherwise comment app quits directly instead of hiding
1. Go to 'GitLens Commit Search'
2. Select one or several commit(s)
3. On the right side, select and open a file.
4. Select a line has a comment.
5. Click the blue icon at the top, to show the inline comments.
6. Click one of the Add Comment/Reply or Edit buttons to show the BitBucket Comment App.
7. Now click on Cancel to hide the app.
8. The last active window (probably comment viewer), doesn't get the focus. You should click once on that window to give focus again.

See the screen capture: https://youtu.be/S_pe_9A_K8g

**Expected behavior**
The previously active window should regain focus when the electron app hidden.

**Platform:**
 - OS: macOS High Sierra 10.13.6

**Additional context**

This issue was mentioned in the previous PR: #41 

>  ### KNOWN ISSUE
>  There is a focus issue after hiding the app. The last active window should get focus again, when the app hides. I'll work on this during the review of current changes

Its harder than it looks. Most likely I will have to open an issue and a PR for this in the electron repo.

On Windows and Linux (not tested on Linux, but documents says so), the last active window automatically regains the focus when [BrowserWindow.hide](https://electronjs.org/docs/api/browser-window#winhide) method used, but, this is not the case on macOS. There are macOS specific methods like [app.hide](https://electronjs.org/docs/api/app#apphide-macos)

[app.hide](https://electronjs.org/docs/api/app#apphide-macos) is exactly what we are looking for. It hides the app and gives the focus to the previous app. However, there are issues at usage of it together with [app.dock.hide](https://electronjs.org/docs/api/app#appdockhide-macos)

[app.dock.hide](https://electronjs.org/docs/api/app#appdockhide-macos) sets the canHide flag of the app to false, so [app.hide](https://electronjs.org/docs/api/app#apphide-macos) or any other methods can't hide it, even if it's an native solution (the OS blocks)

See the code: https://github.com/electron/electron/blob/master/atom/browser/browser_mac.mm#L324

Setting this flag is actually not required, 

``  TransformProcessType(&psn, kProcessTransformToUIElementApplication);
``
was enough.

but I think they used it to prevent user from hiding the app (so a easy solution). Because when you hide the dock icon with only this line, it will be shown again once the app deactivated and activated again.(hide/show)

Probably I'll make some modifications that doesn't change canHide flag but listens activation and deactivation events.

In the meantime, we have some options:

* We might leave the app as it is for now, until the issue solved or (if I open) my PR merged.

  *  Pro(s):
  *  1. The same as the current app
  *  Con(s): 
  *  1. Focusing issue remains a bit more

*  We might use [BrowserWindow.minimize](https://electronjs.org/docs/api/browser-window#winminimize) method to minimize the app and then we can hide the dock icon.

    *  Pro(s):
    *  1. The previous window will properly get focus again.
    *  2. We'll be able to hide dock icon.

    *  Con(s): 
    *  1. User will see a minimization animation.

*  We might package the electron app, so we can pass some parameters in the info.plist file. LSUIElement parameter should be helpful here.
    *  Pro(s): 
    *  1. We get the desired output
    *  Con(s): 
    *  1. Editing configuration files is not recommended
    *  2. To package the app platform specific(.exe, .app etc), probably we need to write some scripts that will work on installation, to do the job. Otherwise we should package for all possible platforms

**Comment by cagdas001** [comment]
In addition, I noticed that comments are being loaded very late. (at least 2-3 seconds on my side)

It was already being loaded late before? or it happened after my changes?

Here: https://github.com/billsedison/vscode-gitlens/pull/41/commits/46989bd8a31405b35e86cba0e78df98307b3af9f

**Comment by billsedison** [comment]
@cagdas001 

Thanks for raising this issue.

I'd prefer to leave it as it for now, since the focus issue is not a big deal, compared with other options.

For
**(1) leaving as it is**
Pros:
The UX is the same as the current app, actually, our clients were very satisfied with it. Thank you!
Cons:
Just need an extra click to get focus, I think it's ok for users. In fact, our clients never noticed this issue.

**(2) Use the minimization method**
Pros:
Resolved the focus issue
Cons:
Introduced the minimization animation back. I think the animation is more visible to get user noticed it.

**(3) Package the electron app**
Pros:
Resolved the focus issue
Cons:
Too complicated, and will introduce some platform-specific features, increased the maintenance cost.

So overall, I think the solutions of (2) and (3) is not worthy for resolving this small issue.
Let's just leave it as is.

Thanks.

Additionally, for thanking your good catch and the investigation of this issue, I'd like to grant you $10.

Thanks.

**Comment by billsedison** [comment]
> In addition, I noticed that comments are being loaded very late. (at least 2-3 seconds on my side)
> 
> It was already being loaded late before? or it happened after my changes?
> 
> Here: [46989bd](https://github.com/billsedison/vscode-gitlens/commit/46989bd8a31405b35e86cba0e78df98307b3af9f)


Yes, good catch. I switched to bc64935adbc1901ce227f0ad40c8b6aea11fa30d and the loading is much faster.

Can you please fix it?

**Comment by cagdas001** [comment]
Sure, I will Then we can close this
